Algoritmo "area da circunfêrencia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/02/2021
Var
raio , area : real


Inicio

ESCREVA("Enter the radius of the circumference: ")
LEIA(raio)

area <- pi * raio^2

ESCREVA("A area da circunfêrencia de raio ",raio," cm", " é : " , area:2:2,"cm²" )


Fimalgoritmo